### PR TITLE
Support for Acer Nitro AN515-45

### PR DESCRIPTION
**Pull request by xAlpharax**
tested on the hardware for about a week

### CODE REVIEW

**Comment by letrad** [comment]
Sorry to revive this, but it seems like the maximum fan speed is not the same as it is on Windows with NitroSense. Is there any way to unlock full RPM?

Also this could be a hardware issue, but my fans keep going on and off, when on Auto mode. as in they go 100% and then 0%

**Comment by letrad** [comment]
Towards a seperate config? Sure. I'll try out the 515-54

**Comment by xAlpharax** [comment]
I actually fixed this issue, need to update my PR for it. The fan speed is actually maximum but for some reason it detects lower values. I am not aware if this happens on other new models as well or not.

**Comment by xAlpharax** [comment]
@letrad check this new change in the open PR #94

**Comment by letrad** [comment]
It definitely feels like the max speed is faster (from sound) but my fan keeps turning on and off. I feel like this is just my pc

**Comment by xAlpharax** [comment]
> It definitely feels like the max speed is faster (from sound) but my fan keeps turning on and off. I feel like this is just my pc

The fact is: These thresholds are completely arbitrary and customizable and activate as soon as the temperature spikes above what is configured(you should play around with the threshold section to see what's best for you)

I tried aiming for an overall good config, but everyone has different expectations on how fans should go and when.

**Comment by letrad** [comment]
> I tried aiming for an overall good config, but everyone has different expectations on how fans should go and when.
It's fine man, it's all good.

**Comment by linuxtopia** [comment]
can we use it for `Nitro AN515-44 NHQ9HEY003` ?

**Comment by xAlpharax** [comment]
> can we use it for `Nitro AN515-44 NHQ9HEY003` ?

Yeah, it should, in theory, be all good for that model as well. They re all in the same series and have pretty much the same fans and fan controls.

**Pull request merged**
