### PR TITLE
Fixes NixOS build

### PR DESCRIPTION
**Pull request by abdlrhman08**
runs `include_files.py` with python3 in the `Makefile.in`, so nbfc can be built without errors. I don't believe this is the best fix there is, since nbfc-gui still does not run.

EDIT: `nbfc-qt` now runs correctly with no problem

### CODE REVIEW

**Comment by k3yss** [comment]
Tried this patch and it works!

**Comment by abdlrhman08** [comment]
@k3yss yes, it does :) and now `nbfc-qt` also works. I hope this gets merged

**Comment by braph** [comment]
Thank you for your contribution and for fixing the error.

Would you mind cleaning up the commits and creating a new pull request? This would help keep the repository cleaner.

Thank you again and best regards,

Benjamin

**Comment by braph** [comment]
I applied the changes. Thank you again!

**Comment by abdlrhman08** [comment]
Thank you

**Comment by k3yss** [comment]
@abdlrhman08 @braph Did you try to build this on nixos? I think the problem still persists with the latest commit:

```
error: builder for '/nix/store/ad510f4flviq4a1vq1milc1qjg0sncqy-nbfc-linux.drv' failed with exit code 2;
       last 10 log lines:
       > src/ec_probe.c:606:3: warning: ignoring return value of 'fread' declared with attribute 'warn_unused_result' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wunused-result-Wunused-result8;;]
       >   606 |   fread(header, 1, sizeof(RegisterHeader) - 1, fh);
       >       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       > src/ec_probe.c:626:7: warning: ignoring return value of 'fread' declared with attribute 'warn_unused_result' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wunused-result-Wunused-result8;;]
       >   626 |       fread(hex, 1, 1, fh);
       >       |       ^~~~~~~~~~~~~~~~~~~~
       > gcc -DNDEBUG -DSYSCONFDIR=\"/nix/store/6sqij13vz7n76q49i8b413y1y28fmw4j-nbfc-linux/etc\" -DDATADIR=\"/nix/store/6sqij13vz7n76q49i8b413y1y28fmw4j-nbfc-linux/share\" -DRUNSTATEDIR=\"/run\" -DVERSION=\"0.2.8\" -Wall -Os -flto src/test_model_config.c -o src/test_model_config -lm -s
       > (cd ./nbfc-gui; ./include_files.py qt.py > nbfc-qt.py)
       > /nix/store/i1x9sidnvhhbbha2zhgpxkhpysw6ajmr-bash-5.2p26/bin/bash: line 1: ./include_files.py: cannot execute: required file not found
       > make: *** [Makefile:58: nbfc-gui/nbfc-qt.py] Error 127
       For full logs, run 'nix log /nix/store/ad510f4flviq4a1vq1milc1qjg0sncqy-nbfc-linux.drv'.
error: 1 dependencies of derivation '/nix/store/ljvzm6c4v7ac9gh65kvmx3v0yl4ha6kz-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/4m0ymq50s3k7c1m9yynab8hxqx7a9s3m-unit-script-nbfc_service-start.drv' failed to build
error: 1 dependencies of derivation '/nix/store/2i9hiv6hjs5w2ryykq81jj00q750qh6x-nixos-system-nixos-24.05.20240730.cf05eea.drv' failed to build


```

**Comment by abdlrhman08** [comment]
@k3yss I am currently using my fork, but I do think the last commit won't build. @braph did not use `python3` for running the script in the `Makefile` for some reason. He probably forgot to include it :)

**Comment by braph** [comment]
@k3yss , @abdlrhman08 I now added `python3` to the Makefile. Hope this helps. Please tell me if that fixes it.

Regards,

Benjamin

**Comment by k3yss** [comment]
@braph Works for me!

**Comment by braph** [comment]
@k3yss Thanks, I appreciate your fast response!

**Comment by abdlrhman08** [comment]
Yes, everything works now. Sorry for my late replies. A bit busy with uni. Thank you @braph and @k3yss

**Pull request closed without merging**
